#!/bin/bash -eu
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dashboard_config="$(read_landscape_config '.charts[] | select(.name=="dashboard")')"
dashboard_repo_path=${LANDSCAPE_HOME}/"dashboard"

if [[ $(jq -r ".managed" <<< "$dashboard_config") = "true" ]] ; then
  manage_submodule dashboard
fi

# render identity helm chart values
python generate-values.py \
  --dashboard-repo-path="$dashboard_repo_path" \
  --tls-crt-path="$LANDSCAPE_STATE_HOME/cert/tls.crt" \
  --tls-key-path="$LANDSCAPE_STATE_HOME/cert/tls.key" \
  > "$COMPONENT_STATE_HOME/values.yaml"

# install or upgrade identity
helm upgrade --install \
  --force \
  --wait \
  --values "$COMPONENT_STATE_HOME/values.yaml" \
  --namespace garden \
  dashboard \
  "$dashboard_repo_path/$(jq -r '.path' <<< "$dashboard_config")"
