#!/bin/bash -eu
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This is the automated part of the gardener installation. 
# It deploys certificates, helm-tiller, gardener, sets the garden clusters as seed cluster, and installs identity and the gardener dashboard
# Prerequesites: kubify cluster

base=$(read_landscape_config ".clusters.base_cluster" | tr "[:lower:]" "[:upper:]")
order_variable="COMPONENT_ORDER_${base}"

if [ $# -gt 1 ]; then 
    parse_args_list ":" comps $2
else 
    comps=
fi

parse_args_list "," order "${!order_variable}"

start_comp="${comps[0]:-${order[0]}}"
end_comp="${comps[1]:-${order[-1]}}"
started=

echo "Deploying components '${start_comp}' to '${end_comp}' ..."

for comp in ${order[@]} ; do
    if [ $comp = $start_comp ] ; then
        started="yes"
    fi

    if [[ -n $started ]] ; then
        if [[ $start_comp = "kubify" ]] && [[ $comp = "etcd" ]] ; then
            : # special case: if deploying with kubify, skip etcd
        else
            deploy "$comp"
        fi
    fi 

    if [ $comp = $end_comp ] ; then
        break
    fi
done

echo ""
echo "Finished deploying components '${start_comp}' to '${end_comp}'."