#!/bin/bash -e
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

python generate-values.py > "$COMPONENT_STATE_HOME/csr.json"

if [ ! -f "$COMPONENT_STATE_HOME/ca-config.json" ] ; then
    cp "${COMPONENT_TEMPLATE_HOME}/ca-config.json" "$COMPONENT_STATE_HOME/ca-config.json"
fi

if [ ! -f ${COMPONENT_STATE_HOME}/tls.crt ] ; then
    cfssl gencert -ca=${KUBIFY_STATE_PATH}/gen/assets/tls/ca.crt -ca-key=${KUBIFY_STATE_PATH}/gen/assets/tls/ca.key -config=${COMPONENT_STATE_HOME}/ca-config.json -profile=server ${COMPONENT_STATE_HOME}/csr.json | cfssljson -bare server
    mv ${COMPONENT_TEMPLATE_HOME}/server-key.pem ${COMPONENT_STATE_HOME}/tls.key
    cat ${COMPONENT_TEMPLATE_HOME}/server.pem ${KUBIFY_STATE_PATH}/gen/assets/tls/ca.crt >${COMPONENT_STATE_HOME}/tls.crt
    rm ${COMPONENT_TEMPLATE_HOME}/server.pem
    mv ${COMPONENT_TEMPLATE_HOME}/server.csr ${COMPONENT_STATE_HOME}/tls.csr
fi
