#!/bin/bash -eu
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source $COMPONENT_TEMPLATE_HOME/prepare.sh deploy

if [[ $entry = "null" ]] ; then
  # CNAME entry not there, create one
  echo "Creating CNAME entry ..."
  aws route53 change-resource-record-sets --hosted-zone-id "$hosted_zone" --change-batch "$change_batch" --profile "$AWS_CLI_PROFILE" 1> /dev/null
else 
  # CNAME entry there, check for correctness
  value=$(jq -r ".ResourceRecords[0].Value" <<< $entry)
  if [[ $value != $ip ]] ; then
    # CNAME entry is there, but wrong
    echo "CNAME entry exists, but value is wrong."
    if [[ $# -gt 1 ]] && [[ $2 = "--force" ]] ; then
      # force argument is set -> overwrite existing cname entry
      echo "Overwriting existing entry ..."
      aws route53 change-resource-record-sets --hosted-zone-id "$hosted_zone" --change-batch "$change_batch" --profile "$AWS_CLI_PROFILE" 1> /dev/null
    else
      echo "Existing entry has not been changed. Add '--force' to overwrite the existing CNAME entry."
    fi
  else 
    echo "CNAME entry already exists. Nothing to do."
  fi
fi

source $COMPONENT_TEMPLATE_HOME/cleanup.sh