#!/bin/bash -eu
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mkdir -p ${KUBIFY_STATE_PATH}

echo "Filling template from landscape.yaml ..."
mako-render base.template > $LANDSCAPE_HOME/terraform.tfvars

echo "Kubify prepare $CLOUD_VARIANT"
$KUBIFY_REPO_PATH/bin/prepare $CLOUD_VARIANT

echo "Kubify apply"
$KUBIFY_REPO_PATH/bin/apply -y

cp $KUBIFY_STATE_PATH/gen/assets/auth/kubeconfig $LANDSCAPE_HOME/kubeconfig
mkdir -p $LANDSCAPE_STATE_HOME/etcd
cp $KUBIFY_STATE_PATH/gen/assets/tls/etcd-client-ca.crt $LANDSCAPE_STATE_HOME/etcd/etcd-ca.pem
cp $KUBIFY_STATE_PATH/gen/assets/tls/etcd-client.crt $LANDSCAPE_STATE_HOME/etcd/etcd-client.pem
cp $KUBIFY_STATE_PATH/gen/assets/tls/etcd-client.key $LANDSCAPE_STATE_HOME/etcd/etcd-client-key.pem

# wait until cluster  is completely running
./wait_for_cluster.sh