#!/bin/bash -eu
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# remove ingress annotations
dashboard_issuer=$(kubectl get ingress -n garden  gardener-dashboard-ingress -o jsonpath="{.metadata.annotations.certmanager\.k8s\.io/cluster-issuer}")
if [ "$dashboard_issuer" = "letsencrypt" ] ; then
    kubectl -n garden annotate ingress gardener-dashboard-ingress certmanager.k8s.io/cluster-issuer- certmanager.k8s.io/acme-dns01-provider- certmanager.k8s.io/acme-challenge-type-
fi

identity_issuer=$(kubectl get ingress -n kube-system  identity-ingress -o jsonpath="{.metadata.annotations.certmanager\.k8s\.io/cluster-issuer}")
if [ "$identity_issuer" = "letsencrypt" ] ; then
    kubectl -n kube-system annotate ingress identity-ingress certmanager.k8s.io/cluster-issuer- certmanager.k8s.io/acme-dns01-provider- certmanager.k8s.io/acme-challenge-type-
fi

# delete certmanager
releases=$(helm list cert-manager --output=json | jq ".Releases | length")
if [ ${releases:-0} -ge 1 ]; then
  helm delete --purge cert-manager
fi
if [ -f $COMPONENT_STATE_HOME/cert-manager-issuer.yaml ] ; then
  kubectl delete -f $COMPONENT_STATE_HOME/cert-manager-issuer.yaml --ignore-not-found
fi
kubectl delete crd issuers.certmanager.k8s.io clusterissuers.certmanager.k8s.io certificates.certmanager.k8s.io --ignore-not-found
kubectl delete ns certmanager --ignore-not-found
