#!/bin/bash -eu

for i in ${COMPONENT_TEMPLATE_HOME}/*.tmpl ; do
    filet=$(basename $i)
    file=${filet::-5}
    mako-render $i > ${COMPONENT_STATE_HOME}/$file
done

# deploy

for i in ${COMPONENT_STATE_HOME}/*.yaml ; do
    echo deploying $i
    kubectl apply -f $i
done
