#!/bin/bash -eu
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

shift # eat "seed-config" argument given do deploy/undeploy script
source $COMPONENT_TEMPLATE_HOME/get_seeds.sh

# render files for all specified seeds
for seed in "${seeds[@]}"; do
    debug "Generating config files for seed: $seed"
    for template in ${COMPONENT_TEMPLATE_HOME}/*.tmpl ; do
        filet=$(basename $template)
        file=${filet/%'.yaml.tmpl'/'-'$seed'.yaml'}
        if [ ! -f ${COMPONENT_STATE_HOME}/$file ]; then # create yaml if it doesn't exist
            mako-render $template > ${COMPONENT_STATE_HOME}/$file --var seed=$seed
        fi
    done
done

# iterate over all files in the state folder that belong to specified seeds
# deploy resources
for seed in "${seeds[@]}"; do
    for i in ${COMPONENT_STATE_HOME}/*$seed.yaml ; do
        echo deploying $i
        kubectl apply -f $i
    done
done