#!/bin/bash -eu
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

shift # eat "seed-config" argument given do deploy/undeploy script
source $COMPONENT_TEMPLATE_HOME/get_seeds.sh

# iterate over all files in the state folder that belong to specified seeds
# delete resources
for seed in "${seeds[@]}"; do
    for i in $(ls -r ${COMPONENT_STATE_HOME}/*$seed.yaml); do # iterate over files in reverse order
        kubectl delete -f $i --ignore-not-found
        rm -f $i
    done
done
rmdir $COMPONENT_STATE_HOME &> /dev/null || true # will delete the state folder if it's empty
