#!/bin/bash -eu
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# initialize helm
kubectl -n kube-system get serviceaccount tiller || \
  kubectl -n kube-system create serviceaccount tiller
kubectl get clusterrolebinding tiller || \
  kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --upgrade --service-account tiller

# wait until helm/tiller to become available
max_retry_time=300
retry_stop=$(($(date +%s) + max_retry_time))
success=false
set +e
while [[ $(date +%s) -lt $retry_stop ]]; do
  sleep 1
  if echo helm version &> /dev/null; then
    success=true
    break;
  fi
  echo -e "$(debug Helm Tiller is not yet available/ready. Waiting...)"
done
set -e
if ! $success; then
  fail "Helm Tiller did not become available/ready within $max_retry_time seconds!"
fi
